name: Go Example Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6' # Executa a cada 15 minutos de segunda a sábado

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        run: |
          go mod init aula-05-artifact || echo "Module already initialized"

      - name: Build for Linux
        run: go build -o ${{ env.FILE_NAME }} ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ${{ env.FILE_NAME }}.exe ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    name: Download and run Linux
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout repository
        uses: a
